# Generated by Django 3.0.4 on 2020-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenroll',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('E', 'Enrolled'), ('D', 'Denied')], default='E', max_length=1),
        ),
    ]
